spring:
  application:
    name: aris-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/aris?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Ananya@790690}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

logging:
  file:
    name: logs/aris.log

server:
  port: 8080

aris:
  ai-engine:
    url: ${ARIS_AI_ENGINE_URL:http://localhost:8000}